### ISSUE TITLE
DS Audio Documentation / Interface Update

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#25]
Update the DS Audio related APIs with regards to source and sink devices
Deprecate the APIs which are not used by both sink and source devices

**Comment by hari22yuva** [comment]
@krishna-1809 Update the description

**Comment by Ulrond** [comment]
@krishna-1809 - please check that you develop branch is set correctly for this change, and can you expand the description, what is this specifically for? Upgrading the documentation, upgrading the header file, both? It's unclear from the ticket what your trying todo here.
