### ISSUE TITLE
Deprecate dsEnableDTCP() & dsEnableDTCP() from DS Video Port

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#30]
dsEnableDTCP() and dsEnableDTCP() are not used in both sink and source devices. It either returns dsERR_OPERATION_NOT_SUPPORTED or just a stub function returning dsERR_NONE.

So deprecating these APIs

**Comment by hari22yuva** [comment]
merged to develop
