### ISSUE TITLE
dsVideoPort Interface Update

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#39]
**1. What will be expected If we set dsSetForceHDRMode()/dsResetOutputToSDR() while playing the HDR streams and update the interface for the same.**

Both will return OPERATION_NOT_SUPPORTED in Sink

dsSetForceHDRMode - Currently No implementation 
dsResetOutputToSDR - Currently returns dsERR_NONE

**2. Please check setforcedisable4ksupport() need to remove form the interface file as it’s not implemented for both sink & source.**

Please refer this link - It is required for Source devices. Currently it must return NOT_SUPPORTED but in future it will be useful for Non UHD cases https://github.com/rdkcentral/rdk-halif-device_settings/pull/16#discussion_r1567595957

**3. In case of Color Capabilities need to check which function used in middle ware keep those API’s only, rest will be removed and what will be default values that also need to update in interface**

Default values for sink:

*color_depth = 10;

*color_space = dsDISPLAY_COLORSPACE_RGB;

**Comment by hari22yuva** [comment]
merged to develop
