### ISSUE TITLE
DS HDMI IN - Architectural comments

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#47]
Interface update:

Select Zoom mode - Is the Select port required before calling the 'select zoom mode'? (Source)

GetCurrentVideoMode, dsHdmiInVideoModeUpdateCB_t - The 'stereoScopicMode' in the 'dsVideoPortResolution_t' is not used and needs to be updated in the interface.

**Comment by hari22yuva** [comment]
merge to develop
