### ISSUE TITLE
dsHDMIIn - HAL Interface file update with SEI signalling info

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#53]
During TV Setting review, it has been suggested by the architect team to provide a note on how the SEI info is being handled for the Picture mode events in the HAL Interface file (dsHDMIIn).  So the function dsHdmiInRegisterAviContentTypeChangeCB should be updated with a note saying " For IP and Tuner Video source, the Picture mode events are updated through SEI info handled from TVSettings module" 

 

Below is the Architecture team feedback.

"As soon as I see "This applies only to IP video sources and Tuner video sources" I ask the question "then where do I get it for HDMI?". So to avoid having to hunt state it. It make life easier and the interface better."

**Comment by hari22yuva** [comment]
Merged to develop
