### ISSUE TITLE
DS FP - Archiectural comments

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#57]
1. All the 7Seg FPD related API’s will now go with a note saying “deprecated” 
2. Precondition Update:
@pre dsFPInit() & dsSetFPState() must be called and  FP State must be "ON" before calling this API
3. The interface file should be updated with  the details on when the blink will be stopped after calling dsSetFPBlink
4. Default value for brightness to be updated in Interface
5. If there is any persistence support for the brightness

**Comment by hari22yuva** [comment]
merged to develop
