### ISSUE TITLE
[dsAudio] Questions on dsAudio interfaces 

### ISSUE THREAD

**Issue by pradeeplawrence** [rdkcentral/rdk-halif-device_settings#6]
In file dsAudio.h
**dsError_t  dsGetAudioEncoding(intptr_t handle, dsAudioEncoding_t *encoding);**
Does it also support for Digital output format?
Seems duplicate with dsGetStereoMode()

**Comment by hari22yuva** [comment]
This API is not used by Middleware to take any actions. For the time being implementation can be stubbed

**Comment by hari22yuva** [comment]
> In file dsAudio.h *_dsError_t dsGetAudioEncoding(intptr_t handle, dsAudioEncoding_t _encoding);__ Does it also support for Digital output format? Seems duplicate with dsGetStereoMode()


This API is not used by Middleware to take any actions. For the time being implementation can be stubbed

**Comment by srinivasgtl** [comment]
No change is required. It is a clarification issue.
