### ISSUE TITLE
Remove statement for Operation_Not_Supported in Get and SetFPState()

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#62]
dsSetFPState() and dsGetFPState() has the below statement :

 * It must return dsERR_OPERATION_NOT_SUPPORTED if the indicator is single-colored or if the FP State is "OFF".
 
 This does not hold true as FP state can be retrieved or set though it is a Single coloured LED. Also OFF is also a valid FP state 
 
 typedef enum __dsFPDState_t
{
    dsFPD_STATE_OFF=0,  ///< FPD State Disable
    dsFPD_STATE_ON,     ///< FPD State Enable
    dsFPD_STATE_MAX,    ///< Out of range 
}dsFPDState_t;

**This issue is created to remove the below statement from dsSetFPState() and dsGetFPState():**

* It must return dsERR_OPERATION_NOT_SUPPORTED if the indicator is single-colored or if the FP State is "OFF".

**Comment by srinivasgtl** [comment]
This issue is now merged.
