### ISSUE TITLE
Add back the Deprecated APIs to resolve DS related build issues

### ISSUE THREAD

**Issue by krishna-1809** [rdkcentral/rdk-halif-device_settings#74]
The removal of deprecated APIs causes DS related errors.

Adding back the deprecated APIs.

These APIs can be removed from interface after doing a complete clean up on all layers

DS Audio:

dsResetBassEnhancer
dsResetSurroundVirtualizer
dsResetVolumeLeveller
dsResetDialogEnhancement
dsSetAudioDucking
dsGetHDMIARCPortId
dsIsAudioLoopThru
dsEnableLoopThru
dsGetAudioDB
dsSetAudioDB
dsGetAudioMaxDB
dsGetAudioMinDB
dsGetAudioOptimalLevel
dsSetAudioEncoding
dsGetAudioEncoding
dsGetAudioDelayOffset
dsSetAudioDelayOffset
DS Video Port:
dsSetActiveSource
dsEnableDTCP
dsIsDTCPEnabled

**Comment by srinivasgtl** [comment]
@krishna-1809 ,  Please add more details on what kind of issues we are seeing with these API's.

**Comment by srinivasgtl** [comment]
Do we still have this requirement?

**Comment by krishna-1809** [comment]
This PR is not required anymore as all corresponding dependencies has been added in HAL .HAL changes are in sync with latest header tag version
